PROXMOX_HOST: ENC[AES256_GCM,data:4GM9DISEO9NabiMP3Egbftij+c9E/fjtBVui6c+Fy7vDZQ==,iv:4OcDs4MWo9/caIRKnJXTMRPN3cutJC6COFJSMZds0Tw=,tag:V88D3HikulcQMqwQ03hYXA==,type:str]
PROXMOX_API_TOKEN: ENC[AES256_GCM,data:E+d5MIklWXwxXRGfkdvGMq1nBs70m0mcGVMlODXqPyr7IJo8ZLFwMjpm0+cgzL5k1m+jZ/21Hp4=,iv:arXaiv6pU0yq1AYskPaJzWJCGi2lg5gKrrJVXcZ3Ivg=,tag:YP0WHiDxvi0pXRbxze5ZOA==,type:str]
sops:
    age:
        - recipient: age1595c6n7r3zu0aql8qeehlulds6g4cvavmphsyauk9uddks5hpuzqcg7c4u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwN3VFVjZYd3pnVUl2N0Z5
            azNnZmRaNjRiNUszVm9EdlVOYjlmQnZjcGg4CkdtVE1mOEZoR1hKUk42cms1ekIy
            M1JjOU5maGQ2bzV5OVYxNUpXcGl2RUUKLS0tIHk2WFlUMjFaUkx2MW52YkRxUlN4
            MzJrZ0dDMlFVNS8zRkVIWGxKYm9qclEKX6qfUb2nUv6k2bBqmho+5Bn4dkim0E5r
            tSWqdWCAWeWBhsZsB2cscq/nekQXI9TG+g4x9O+JwjMI6IZQePE1JQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-25T20:10:02Z"
    mac: ENC[AES256_GCM,data:GJrc5ykdrl8PXsXAdHpR3CG46rFrjMgNnrOfXF5ThaRO48o1iwc1ss53TlMV5o6f/vMwrf+ezo1rCws7ARmPRkOC4I76XQ6YTo7dE/ZLkyJYND6K3Y+PmcSKwM3Qil0+BsOQcyh/0WVe95Nayu6A5MEEcpx5CChQZv+sQEto2Oc=,iv:0vXgse3lWREqCH5QByJQrw7xxMRuxm3NA+81upCoQk4=,tag:OcjE0HprPxepmcIFB4hf5A==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
