PROXMOX_TOKEN_SECRET: ENC[AES256_GCM,data:UPnuIwELMc/HNtcUKuN82kS0muOriMuC2oK28jZAks32l8de,iv:bb8VqLI09vRlV14BD4Gjm66pnz5dvH0CE9ZRJeHPCuw=,tag:ywNAM49zknahBCmvmymn8g==,type:str]
PROXMOX_TOKEN_KEY: ENC[AES256_GCM,data:+69JXAGOTxMH8g==,iv:hXYCPl7WXzSBL7ayUFkIpLqHbqVzZ9jAGy4+4sJV+1k=,tag:s2tyJmrhF32Y9iY01NNBLg==,type:str]
PROXMOX_USER: ENC[AES256_GCM,data:iZ0LXA==,iv:5rc2TZ2tGJdK6aRMPp4EPUkpwijmrUL00tEG+Om3NiA=,tag:Ae7p43Yjgu07LirrOAL08Q==,type:str]
PROXMOX_REALM: ENC[AES256_GCM,data:yuT7,iv:VpDIWcVnhaw8WCaD8Ztr8TyF4RiTritg6JopqarXWwQ=,tag:Suo7a7rCho45fjQoQ5Kftg==,type:str]
PROXMOX_HOST: ENC[AES256_GCM,data:HwHtrSbcX5Stsi87Wa/5OcFxnwIk,iv:C9WUZFDjHldF2A2Vcij9ln3ylbpKpZXZ4EGMn0YMobg=,tag:3TkRrbjn16JWsowhMdjD2A==,type:str]
PROXMOX_PORT: ENC[AES256_GCM,data:82aaJQ==,iv:ariO7GAezEuhj+u7OouFkPZNbdeJ6O/qkiWzH/QN0x4=,tag:55j3JxXc2T0d0AT8kKkfhw==,type:int]
PROXMOX_REJECT_UNAUTHORIZED: ENC[AES256_GCM,data:X7Aqs/c=,iv:twPEf3deZVkVJAv1WtY4wO4YEsL8ttpOWV5weU0hFb0=,tag:Ui6shTdjJiUiFfKVBgOWGw==,type:bool]
sops:
    age:
        - recipient: age1595c6n7r3zu0aql8qeehlulds6g4cvavmphsyauk9uddks5hpuzqcg7c4u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwN3VFVjZYd3pnVUl2N0Z5
            azNnZmRaNjRiNUszVm9EdlVOYjlmQnZjcGg4CkdtVE1mOEZoR1hKUk42cms1ekIy
            M1JjOU5maGQ2bzV5OVYxNUpXcGl2RUUKLS0tIHk2WFlUMjFaUkx2MW52YkRxUlN4
            MzJrZ0dDMlFVNS8zRkVIWGxKYm9qclEKX6qfUb2nUv6k2bBqmho+5Bn4dkim0E5r
            tSWqdWCAWeWBhsZsB2cscq/nekQXI9TG+g4x9O+JwjMI6IZQePE1JQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-26T08:17:21Z"
    mac: ENC[AES256_GCM,data:tQ4JhgLUxlFvneob25St0YUjE73CnlgqGOmOIFW968NdHj8c9miU3UrdLYasl8QkM5U8zzj60YtTBDebiNGnDvazukVGlZiJY+WckJTP49W845+RBEc+GL2VOQVILHMggMKYbp0Zxyc3/aDgBVxUfarTjAN2WvN4SjiAyLl6rl0=,iv:VEN21IDNL1NNWsKvC7YWFzXEOQkY9CcJBmfiEcIhXcc=,tag:lPylEDOWWJmgDkxtipmHqA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
