PROXMOX_TOKEN_SECRET: ENC[AES256_GCM,data:UPnuIwELMc/HNtcUKuN82kS0muOriMuC2oK28jZAks32l8de,iv:bb8VqLI09vRlV14BD4Gjm66pnz5dvH0CE9ZRJeHPCuw=,tag:ywNAM49zknahBCmvmymn8g==,type:str]
PROXMOX_TOKEN_KEY: ENC[AES256_GCM,data:+69JXAGOTxMH8g==,iv:hXYCPl7WXzSBL7ayUFkIpLqHbqVzZ9jAGy4+4sJV+1k=,tag:s2tyJmrhF32Y9iY01NNBLg==,type:str]
PROXMOX_USER: ENC[AES256_GCM,data:iZ0LXA==,iv:5rc2TZ2tGJdK6aRMPp4EPUkpwijmrUL00tEG+Om3NiA=,tag:Ae7p43Yjgu07LirrOAL08Q==,type:str]
PROXMOX_REALM: ENC[AES256_GCM,data:yuT7,iv:VpDIWcVnhaw8WCaD8Ztr8TyF4RiTritg6JopqarXWwQ=,tag:Suo7a7rCho45fjQoQ5Kftg==,type:str]
PROXMOX_HOST: ENC[AES256_GCM,data:HwHtrSbcX5Stsi87Wa/5OcFxnwIk,iv:C9WUZFDjHldF2A2Vcij9ln3ylbpKpZXZ4EGMn0YMobg=,tag:3TkRrbjn16JWsowhMdjD2A==,type:str]
PROXMOX_PORT: ENC[AES256_GCM,data:82aaJQ==,iv:ariO7GAezEuhj+u7OouFkPZNbdeJ6O/qkiWzH/QN0x4=,tag:55j3JxXc2T0d0AT8kKkfhw==,type:int]
sops:
    age:
        - recipient: age1595c6n7r3zu0aql8qeehlulds6g4cvavmphsyauk9uddks5hpuzqcg7c4u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwN3VFVjZYd3pnVUl2N0Z5
            azNnZmRaNjRiNUszVm9EdlVOYjlmQnZjcGg4CkdtVE1mOEZoR1hKUk42cms1ekIy
            M1JjOU5maGQ2bzV5OVYxNUpXcGl2RUUKLS0tIHk2WFlUMjFaUkx2MW52YkRxUlN4
            MzJrZ0dDMlFVNS8zRkVIWGxKYm9qclEKX6qfUb2nUv6k2bBqmho+5Bn4dkim0E5r
            tSWqdWCAWeWBhsZsB2cscq/nekQXI9TG+g4x9O+JwjMI6IZQePE1JQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-26T07:23:00Z"
    mac: ENC[AES256_GCM,data:xJooU6f2hInGKqFToYp4t0BoACALHSjxi5vXS9N/TSXL2qctn9KZOmtfVW1RWpD8i2zJKsE4IiUrL8zEP9C1OXNTVV8ikkmD6e1MUBA65G+439lUVKfJQHPLlzENaOYOYMm1fIKGBl3G3FJirul54VbsedN+Wmc7NMVXzEc84FQ=,iv:lPNbkMbrUZ64Z1ZG/zNzrAEVtUiIcHsI6wW+EGSxy/s=,tag:Fe1/i+RHB3oXFRcxu0ygnA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
