#!/usr/bin/env bash

TEMPLATE_NAME="tpl-linux-ubuntu-server-24.04"
IP_ADDRESS="192.168.1.89"

# create a new VM from the template and capture the json output
OUTPUT=$(bin/dev.js proxmox vm create "$TEMPLATE_NAME" "test" --json)

# parse the output with jq and extract the vmid to a variable
VMID=$(echo "$OUTPUT" | jq -r '.vmid')

bin/dev.js proxmox vm cloudinit "$VMID" --ipconfig ip=$IP_ADDRESS/24

sleep 5

bin/dev.js proxmox vm start $VMID

sleep 10

ssh -i ~/.ssh/admin_id_ecdsa -o StrictHostKeyChecking=no admin@$IP_ADDRESS "echo 'SSH connection to VM $VMID successful'"

bin/dev.js proxmox vm stop $VMID
